LEVEL_MAP = [
'XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYX',
'YXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY',
'XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYX',
'YXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY',
'XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYX',
'YXYXYXYXYX                                     XYXYXYXYXY',
'XYXYXYX                                          YXYXYXYX',
'YXYXYX                                            YXYXYXY',
'XYXYX                             XYXYXYXYXYXYX   XYXYXYX',
'YXYX                              YXYXY          XYXYXYXY',
'XYXY      YXYX                  XYXYXY          XYXYXYXYX',
'YXYX                            YXYXY   YXYXYXYXYXYXYXYXY',
'XYXYXY             YXY        XYXYXYX            YXYXYXYX',
'YXYXYX                        YXYXYXYX            YXYXYXY',
'XYXYXY                   YXYXYXYXYXYXYXYX         XYXYXYX',
'YXYXYXYX               XYXYXYXYXYXYXYXYXYXYX      YXYXYXY',
'XYXYXY                  XYXYXYXY          XYX     XYXYXYX',
'YXYXY       XYX          XYXYX                    YXYXYXY',
'XYXYXP                   YXY       YXYXY         YXYXYXYX',
'YXYXY             XYX    XY      XYXYXYXYXYXYXYXYXYXYXYXY',
'XYXYXY                  XYX        YXYXY         YXYXYXYX',
'YXYXYXY    CCC         XYXYX                       XYXYXY',
'XYXYXYXYXYXYXYXYXYXYXYXYXYXYX                      YXYXYX',
'YXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY                   YXYXYXY',
'XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYX',
'YXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY',
'XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYX',
'YXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY'
'XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYX']

TILE_SIZE = 32
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

level = 0
max_levels = 10
score = 0

# colors
BG_COLOR = '#1a472a'
PLAYER_COLOR = '#FF0000'
TILE_COLOR = '#00b8b8'

COIN_COLOR = '#FFFF00'
TILE2_COLOR = '#108686'
END_COLOR = '#FFA500'

# camera
CAMERA_BORDERS = {
	'left': 100,
	'right': 200,
	'top': 100,
	'bottom': 150
}